services:
#  nginx:
#    container_name: ptplot-nginx
#    image: nginx
#    # volumes:
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      - web
#    labels:
#      - "com.centurylinklabs.watchtower.scope=ptplot"
#    restart: always
  web:
    container_name: ptplot-web
    build: .
    env_file:
      - ./env/django.env
    ports:
      - "8000:8000"
    labels:
      - "com.centurylinklabs.watchtower.scope=ptplot"
    restart: always
  watchtower:
    container_name: ptplot-watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    # Run once a week on Sunday at 04:45
    command: --cleanup --schedule "0 45 4 * * 0" --scope ptplot
    labels:
      - "com.centurylinklabs.watchtower.scope=ptplot"
    restart: always
