services:
#  nginx:
#    container_name: ptplot-nginx
#    image: nginx
#    # volumes:
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      - web
#    restart: always
  web:
    container_name: ptplot-web
    # build: .
    image: cfthy/ptplot:main
    env_file:
      - ./env/django.env
    ports:
      - "8000:8000"
    restart: always
    labels:
      - "wud.tag.include=main"
      - "wud.trigger.include=dockercompose.ptplot,smtp.ptplot"
      - "wud.watch=true"
      - "wud.watch.digest=true"
  whatsupdocker:
    image: getwud/wud:latest
    container_name: ptplot-wud
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./wud/store:/store
      - ./docker-compose.yml:/wud/compose/docker-compose.yml
    env_file:
      - env/wud.env
    labels:
      - "wud.trigger.include=dockercompose.ptplot,smtp.ptplot"
      - "wud.watch=true"
