[build-system]
requires = [
    "setuptools",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "ptplot-gw"
version = "1.1.0"
description = "PTPlot tool for plotting phase transitions"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = [
    "cosmology",
    "phase transitions",
    "gravitational waves"
]
authors = [
    {name = "David Weir", email = "david.weir@helsinki.fi"},
    {name = "Deanna Hooper", email = "deanna.hooper@helsinki.fi"},
    {name = "Jenni Häkkinen", email = "jenni.hakkinen@helsinki.fi"},
    {name = "Mika Mäki", email = "mika.x.maki@helsinki.fi"}
]
maintainers = [
    {name = "David Weir", email = "david.weir@helsinki.fi"},
    {name = "Mika Mäki", email = "mika.x.maki@helsinki.fi"}
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Matplotlib",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Operating System :: MacOS",
    "Operating System :: OS Independent",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Windows",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Free Threading :: 1 - Unstable",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed"
]
# Keep this up to date with requirements.txt.
# Please also ensure that compatible versions are available in LISA ProtoLab.
dependencies = [
    "django >= 6.0.5",
    "django-github-sso >= 5.0.2",
    "dulwich >= 1.2.4",
    "gunicorn >= 26.0.0",
    "matplotlib >= 3.10.9",
    "numpy >= 2.4.6",
    "pandas >= 3.0.3",
    "pttools-gw[numbalsoda,performance] == 0.10.0",
    "scipy >= 1.17.1"
]
requires-python = ">= 3.12"
# dynamic = ["version"]

# [project.optional-dependencies]
# pttools = [
#     "pttools-gw[numbalsoda,performance]"
# ]

[project.urls]
homepage = "https://www.ptplot.org"
documentation = "https://ptplot.readthedocs.io"
issues = "https://github.com/CFT-HY/PTPlot/issues"
repository = "https://github.com/CFT-HY/PTPlot"

[tool.coverage.run]
branch = true
command_line = "manage.py test --noinput --parallel"
concurrency = [
    "thread",
    "multiprocessing"
]
source = ["."]
omit = [
    "*/envs/*",
    "*/venv/*",
    "*.txt",
    "docs/_build/*",
    "test-results/*"
]
parallel = true
plugins = ["django_coverage_plugin"]

[tool.coverage.report]
exclude_also = [
    "if __name__ == .__main__.:"
]
show_missing = true

[tool.django-stubs]
django_settings_module = "ptplot_site.settings.dev"

[tool.mypy]
exclude = [
    "_build",
    "auto_examples"
]
files = [
    "docs",
    "examples",
    "ptplot",
    "ptplot_site",
    "tools",
    "manage.py"
]
plugins = ["mypy_django_plugin.main"]

[[tool.mypy.overrides]]
module = ["django_github_sso.*", "debug_toolbar.*", "plotly.*", "sphinx_gallery.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
# On clusters "--numprocesses=auto" creates processes according to the total number of CPU cores
# instead of the number of cores available to the job.
# Therefore, it may be wise to set the number of processes manually.
addopts = [
    "--alluredir=test-results/allure",
    "--cov=.",
    "--cov-report=html",
    "--cov-report=json",
    "--cov-report=term",
    "--cov-report=term-missing",
    "--cov-report=xml",
    "--dist=loadscope",  # This ensures that tests from the same class are run on the same worker.
    "--durations=50",
    "--durations-min=1.0",
    "--html=test-results/html/test-report.html",
    "--numprocesses=auto"
]
DJANGO_SETTINGS_MODULE = "ptplot_site.settings.dev"
testpaths = [
    "ptplot/tests"
]

[tool.setuptools.packages.find]
include = [
    # "ptplot",
    "ptplot.forms*",
    "ptplot.management*",
    "ptplot.migrations*",
    "ptplot.science*",
    "ptplot.static*",
    "ptplot.templates*",
    "ptplot.views*"
]
exclude = [
    "ptplot.tests",
    "ptplot_site"
]
