"""
Django settings for ptplot_site project.

Generated by "django-admin startproject" using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# Application definition
SITE_NAME = "PTPlot"

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ptplot.apps.PTPlotConfig",
    "django_github_sso",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
]

ROOT_URLCONF = "ptplot_site.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "ptplot" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ptplot_site.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "ptplot.User"

# GITHUB_SSO_ALLOWABLE_ORGS = ["CFT-HY"]
GITHUB_SSO_ALWAYS_UPDATE_USER_DATA = True
GITHUB_SSO_NEEDED_REPOS = ["CFT-HY/PTPlot"]
GITHUB_SSO_CLIENT_ID = os.environ.setdefault("GITHUB_SSO_CLIENT_ID", "ChangeMe")
GITHUB_SSO_CLIENT_SECRET = os.environ.setdefault("GITHUB_SSO_CLIENT_SECRET", "ChangeMe")
GITHUB_SSO_SUPERUSER_LIST = [
    "AgenttiX",  # Mika Mäki
    "davidjamesweir",  # David Weir
]
GITHUB_SSO_UNIQUE_EMAIL = True
# SSO_SHOW_FORM_ON_ADMIN_PAGE = False  # Hide username & password login form


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Europe/Helsinki"
USE_I18N = True
USE_TZ = True
DATE_FORMAT = "Y-m-d"
DATETIME_FORMAT = "Y-m-d H:i:s"
TIME_FORMAT = "H:i:s"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email
ADMINS = [
    ("David Weir", "david.weir@helsinki.fi"),
    ("Mika Mäki", "mika.x.maki@helsinki.fi")
]
MANAGERS = ADMINS
DEFAULT_FROM_EMAIL = "ptplot@ptplot.org"
SERVER_EMAIL = DEFAULT_FROM_EMAIL
