name: Publish Docker image
on:
  release:
    types: [published]
  workflow_dispatch:
# The workflow_run trigger works only on the default branch.
#  workflow_run:
#    workflows: [CI]
#    types: [completed]
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      artifact-metadata: write
      attestations: write
      id-token: write
      contents: read
      packages: write
    steps:
      # The image is built from the Git context of the commit, so a checkout is not needed.
      - name: Build and push Docker images
        uses: CFT-HY/pttools/.github/actions/deploy-docker@dev
        with:
          dockerhub-image: cfthy/ptplot
          dockerhub-organization: ${{ vars.DOCKERHUB_ORGANIZATION }}
          dockerhub-oidc-connection-id: ${{ vars.DOCKERHUB_OIDC_CONNECTIONID }}
