name: Publish to Software Heritage Foundation
on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  deploy-shf:
    uses: CFT-HY/pttools/.github/workflows/deploy-shf.yml@dev
