name: CI
on: push
env:
  PRIMARY_PYTHON_VERSION: "3.14"
jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.PRIMARY_PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Print Python version
        run: python -V
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install --upgrade build packaging twine
      - name: Build
        run: python -m build
      - name: Run Twine checks
        run: twine check dist/*
      - name: Upload built artifacts
        uses: actions/upload-artifact@v7
        with:
          name: pip packages
          path: dist
          if-no-files-found: error
  cloc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Count Lines of Code (cloc) for the PTPlot module
        uses: djdefi/cloc-action@6
        with:
          options: ${{ github.workspace }}/ptplot --by-file-by-lang --vcs=git
      - name: Count Lines of Code (cloc) for the repository
        uses: djdefi/cloc-action@6
        with:
          options: ${{ github.workspace }} --by-file-by-lang --vcs=git
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.PRIMARY_PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - name: Print Python version
        run: python -V
      - name: Install requirements
        run: |
          pip install --upgrade pip wheel
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Run Pylint
        run: DJANGO_SETTINGS_MODULE=ptplot_site.settings.dev pylint docs examples ptplot ptplot_site tools conftest.py manage.py 2>&1 | tee pylint.txt
      - name: Upload results
        uses: actions/upload-artifact@v7
        with:
          name: Lint
          path: |
            ${{ github.workspace }}/pylint.txt
          if-no-files-found: error
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.PRIMARY_PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - name: Print Python version
        run: python -V
      - name: Install requirements
        run: |
          pip install --upgrade pip wheel
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Load mypy cache
        uses: actions/cache@v6
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            mypy-${{ runner.os }}-
            mypy-
      - name: Run mypy
        run: mypy ptplot ptplot_site tools 2>&1 | tee mypy.txt
      - name: Upload results
        uses: actions/upload-artifact@v7
        with:
          name: Mypy
          path: |
            ${{ github.workspace }}/mypy.txt
          if-no-files-found: error
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: ptplot_site.settings.dev
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Setup Python
      uses: actions/setup-python@v7
      with:
        python-version: ${{ env.PRIMARY_PYTHON_VERSION }}
        cache: pip
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt
    - name: Print Python version
      run: python -V
    - name: Install requirements
      run: |
        pip install --upgrade pip wheel
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Print Numba sysinfo
      run: numba --sysinfo | tee numba-sysinfo.txt
    - name: Create migrations
      run: python manage.py makemigrations
    - name: Migrate database
      run: python manage.py migrate
    - name: Check configuration
      run: python manage.py check --fail-level WARNING
    - name: Generate PTtools reference data
      run: python3 -c "from pttools.bubble.fluid_reference import ref; ref()"
    - name: Run tests with coverage
      run: |
        set -o pipefail
        pytest --store-durations | tee test-output.txt
    - name: Upload results
      uses: actions/upload-artifact@v7
      with:
        name: Test results
        path: |
          .test_durations
          coverage.xml
          coverage.json
          htmlcov
          test-output.txt
        if-no-files-found: error
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
